apiVersion: v1
kind: Pod
metadata:
  name: restricted-app
spec:
  containers:
  - name: app
    image: restricted_dotnet_docker_app
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
